apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content
  namespace: production
  labels:
    app: blog
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
