apiVersion: v1
kind: ConfigMap
metadata:
  name: blog-nginx
  namespace: production
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location ~ {
        proxy_ssl_server_name on;
        proxy_pass https://pokedextracker.mymidnight.blog:443;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-nginx
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-nginx
  template:
    metadata:
      labels:
        app: blog-nginx
    spec:
      containers:
      - image: nginx:1.17.9-alpine
        name: blog-nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-configs
          mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-configs
          configMap:
            name: blog-nginx
---
apiVersion: v1
kind: Service
metadata:
  name: blog-nginx
  namespace: production
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: blog-nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: blog-nginx
  name: blog-nginx
  namespace: production
spec:
  tls:
  - hosts:
    - pokedextracker.com
  rules:
  - host: pokedextracker.com
    http:
      paths:
      - path: /blog
        backend:
          serviceName: blog-nginx
          servicePort: 80
