apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: wildcard
  namespace: default
spec:
  secretName: wildcard
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "pokedextracker.com"
  - "*.pokedextracker.com"
  - "*.staging.pokedextracker.com"
  acme:
    config:
    - dns01:
        provider: route53
      domains:
      - "pokedextracker.com"
      - "*.pokedextracker.com"
      - "*.staging.pokedextracker.com"
