apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: staging-wildcard
  namespace: default
spec:
  secretName: staging-wildcard
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - "pokedextracker.com"
  - "*.pokedextracker.com"
  - "*.staging.pokedextracker.com"
